spring:
  application:
    name: ms-teachers-management-consumer

  kafka:
    client-id: "${spring.application.name}"
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        group-id: teachers-consumer
    topics:
      teacher-info: ${TOPIC_TEACHER_INFO:teacher-info-topic}

server:
  port: 8081